# Generated by Django 5.2.4 on 2025-07-13 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_user_followers_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.AddField(
            model_name="song",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_song",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
