# Generated by Django 5.2.4 on 2025-07-13 15:55

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_song_artist_song_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="img",
            field=models.ImageField(
                blank=True,
                default="/assets/images/profile.png",
                null=True,
                upload_to=backend.models.avatar_upload_path,
                verbose_name="Playlist Image",
            ),
        ),
    ]
