# Generated by Django 5.2.4 on 2025-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_playlist_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="duration",
            field=models.FloatField(
                blank=True, null=True, verbose_name="duration (seconds)"
            ),
        ),
    ]
