# Generated by Django 5.2.4 on 2025-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_song_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to="backend.song"
            ),
        ),
    ]
