# Generated by Django 5.2.4 on 2025-07-16 13:12

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="assets/profile.png",
                null=True,
                upload_to=backend.models.avatar_upload_path,
                verbose_name="avatar",
            ),
        ),
    ]
