# Generated by Django 5.2.4 on 2025-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="playing_id",
            field=models.IntegerField(default=0, verbose_name="playing_id"),
        ),
        migrations.AddField(
            model_name="user",
            name="playing_list",
            field=models.ManyToManyField(
                blank=True, related_name="user_playing_lists", to="backend.playlist"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="playing_list_id",
            field=models.IntegerField(default=0, verbose_name="playing_list_id"),
        ),
        migrations.AlterField(
            model_name="user",
            name="playlists",
            field=models.ManyToManyField(
                blank=True, related_name="playist", to="backend.playlist"
            ),
        ),
    ]
