# Generated by Django 5.2.4 on 2025-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_remove_user_playing_id_user_playing_music_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="playing_list_id",
        ),
        migrations.AddField(
            model_name="user",
            name="playing_list_music_id",
            field=models.IntegerField(default=0, verbose_name="playing_list_music_id"),
        ),
    ]
