# Generated by Django 5.2.4 on 2025-07-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_remove_user_playing_list_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="playing_music_id",
        ),
        migrations.AddField(
            model_name="user",
            name="playing_music",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currently_playing_song",
                to="backend.song",
            ),
        ),
    ]
