# Generated by Django 5.2.4 on 2025-07-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_remove_user_playing_music_id_user_playing_music"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playlist",
            unique_together={("owner", "name")},
        ),
    ]
