# Generated by Django 5.2.4 on 2025-07-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0018_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="backend.playlist",
            ),
        ),
    ]
