# Generated by Django 5.2.4 on 2025-07-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_notification_playlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
    ]
