# Generated by Django 5.2.4 on 2025-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_remove_notification_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="artist_id",
            field=models.IntegerField(default=0, verbose_name="artist_id"),
        ),
    ]
