# Generated by Django 5.2.4 on 2025-07-24 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0021_notification_artist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="artist_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
