# Generated by Django 5.2.4 on 2025-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_remove_notification_artist_id_notification_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="recently",
            field=models.ManyToManyField(related_name="recently", to="backend.song"),
        ),
    ]
