# Generated by Django 5.2.4 on 2025-07-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_playlist_recently"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="recently",
        ),
    ]
