# Generated by Django 5.2.4 on 2025-07-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0024_remove_playlist_recently"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recently",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="backend.song"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="songs",
            field=models.ManyToManyField(
                blank=True, related_name="recently", to="backend.song"
            ),
        ),
    ]
