# Generated by Django 5.2.4 on 2025-07-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_user_recently_alter_user_songs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="playing_list",
        ),
        migrations.RemoveField(
            model_name="user",
            name="playing_list_music_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="playing_music",
        ),
    ]
